### ISSUE TITLE
New Paper to include

### ISSUE THREAD

**Issue by mgradyn** [SerialLain3170/AwesomeAnimeResearch#11]
Hi! Thought this paper might be worth including!

https://arxiv.org/abs/2208.11012

**Comment by SerialLain3170** [comment]
Thank you for your proposal. I added the paper in [d3cb753](https://github.com/SerialLain3170/AwesomeAnimeResearch/commit/d3cb7533fa8f362cb3ce20f5f786a709f1d33f76)
