### ISSUE TITLE
New paper to include

### ISSUE THREAD

**Issue by CR-Gjx** [SerialLain3170/AwesomeAnimeResearch#14]
Hi! Hope the author can consider including one related paper
https://openaccess.thecvf.com/content/CVPR2022/papers/Guo_Alleviating_Semantics_Distortion_in_Unsupervised_Low-Level_Image-to-Image_Translation_via_Structure_CVPR_2022_paper.pdf

**Comment by SerialLain3170** [comment]
Thank you for the issue, and I am sorry for the late reply.

I added your paper in the [commit](https://github.com/SerialLain3170/AwesomeAnimeResearch/commit/40b22b7cdd525b68bf9cb927cee9d39d1b84b3a1).
