### ISSUE TITLE
New paper and dataset

### ISSUE THREAD

**Issue by Chanuku** [SerialLain3170/AwesomeAnimeResearch#16]
Hi thanks for the awesome page

We have the new paper which is follow-up study of "Reference based sketch extraction via attention mechanism"

new paper's title is "Semi-supervised reference-based sketch extraction using a contrastive learning framework"

it is accepted to upcoming siggraph 2023 journal track (ACM TG 2023)

project page : https://chanuku.github.io/Semi_ref2sketch/
code : https://github.com/Chanuku/semi_ref2sketch_code

And we have new dataset consists of anime image and paired 4 different styles of sketches
dataset (4skst) : https://github.com/Chanuku/4skst

Thank you

**Comment by SerialLain3170** [comment]
Thank you for the beautiful work! I added the paper and the dataset in the [commit](https://github.com/SerialLain3170/AwesomeAnimeResearch/commit/e228db35e52cf8d443de41a603db698c46ff933c).
