### ISSUE TITLE
a Two-Stage Colorization Paper

### ISSUE THREAD

**Issue by gceboh** [SerialLain3170/AwesomeAnimeResearch#3]
Thank you for your paper collection!

Here is a paper about Automatic Line Art Colorization:
Title: **Automatic Colorization of Anime Style Illustrations Using a Two-Stage Generator**

**Comment by gceboh** [comment]
Another paper:
[Colorization of Line Drawings with Empty Pupils](https://www.gwern.net/docs/anime/2020-akita.pdf), which is the extended version of `Deep-Eyes: Fully Automatic Anime Character Colorization with Painting of Details on Empty Pupils`

**Comment by SerialLain3170** [comment]
Thanks! I added these papers in this [commit](https://github.com/SerialLain3170/AwesomeAnimeResearch/commit/0525ba7d86b278b8abc6830dd83fd5d1be8f6668).
