### ISSUE TITLE
New papers to include

### ISSUE THREAD

**Issue by mariana200196** [SerialLain3170/AwesomeAnimeResearch#4]
Hi! Thought these papers might be worth including :)

[ACFD Asymmetric Cartoon Face Detector.pdf](https://github.com/SerialLain3170/AwesomeAnimeResearch/files/7231290/ACFD.Asymmetric.Cartoon.Face.Detector.pdf)
[Cartoon Face Recognition A Benchmark Dataset.pdf](https://github.com/SerialLain3170/AwesomeAnimeResearch/files/7231291/Cartoon.Face.Recognition.A.Benchmark.Dataset.pdf)

**Comment by SerialLain3170** [comment]
Thank you! I added these papers in the [commit](https://github.com/SerialLain3170/AwesomeAnimeResearch/commit/cfa040ec81057990e8fa4ad7438988c58cc5b1b2)
